# Generated by Django 4.1.7 on 2023-03-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaSoTuVi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('nam_sinh', models.IntegerField()),
                ('thang_sinh', models.IntegerField()),
                ('ngay_sinh', models.IntegerField()),
                ('gio_sinh', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('nam_xem_han', models.IntegerField()),
            ],
        ),
    ]
