# Generated by Django 4.1.7 on 2023-03-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lasotuvi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasotuvi',
            name='am_lich',
            field=models.DateField(null=True),
        ),
    ]
